main: me.CoPokBl.EsTools.Main
name: EsTools
version: 1.5
author: CoPokBl
api-version: 1.13

commands:
  gmc: 
    aliases: creative
  gms: 
    aliases: survival
  gma: 
    aliases: adventure
  spec: 
    aliases: sp
  estools: 
  suicide: 
  smite: 
  fly: 
  sudo: 
  sethealth: 
  setmaxhealth: 
  invsee: 
  tphere: 
  tpall: 
  changename: 