# Go to https://estools.serble.net/configuration.html for information on configuring the plugin

# Stops players taking fall damage when they teleport
safeTp: true

# Toggle bStats metrics
metrics: true

# Configure the EsTools auto updater, everything is disabled by default
updater:

  # The GitHub API path to query for the latest version, change if you want to use a fork
  githubReleasesUrl: "https://api.github.com/repos/CoPokBl/EsTools/releases/latest"

  # Whether to automatically install updates if they are available
  autoUpdate: false

  # Whether to notify operators when they join the server if the plugin is outdated
  # Leave this off if you enable auto-update, this will prompt user to type /estools update
  warnOnOutdated: false

  # Log to the console when the plugin is out of date
  logOnOutdated: true
