main: net.serble.estools.Main
name: EsTools
description: Simple highly compatible general purpose plugin. Written for Bukkit beta 1.7.3
version: b7-4.0
authors: [Calcilator, CoPokBl]
api-version: 1.13

commands:
  estools:
    description: View plugin information, including the version.
  tphere:
    description: Teleport a player to you.
  tpall:
    description: Teleport all players to you.
  feed:
    description: Fill saturation and hunger.
  heal:
    description: Heal a player.
  sudo:
    description: Run a command as another player.
  suicide:
    description: End your own life.
  smite:
    description: Strike player with lightning.
  sethealth:
    description: Set a player's health.
  i:
    description: Give yourself an item.
  h:
    description: Put an item in your currently selected slot.
  fix:
    description: Fully repair held item.
  getinfo:
    description: Get information about an entity.
  editsign:
    description: Modify the text on a sign.
  setstack:
    description: Change the size of the held item stack.
    aliases: stack
  ci:
    description: Clear your inventory.
  sun:
    description: Set the time to day.
    aliases: day
  moon:
    description: Set the time to night.
    aliases: night

permissions:
  estools.tp:
    description: Lets people teleport themselves and others
    default: op
    
  estools.feed:
    description: Lets people feed themselves and others
    default: op
    
  estools.heal:
    description: Lets people heal themselves and others
    default: op
    
  estools.sudo:
    description: Lets people run commands as other players
    default: op
    
  estools.suicide:
    description: Lets people kill themselves
    default: true
    
  estools.smite:
    description: Lets people strike lightning on people
    default: op
    
  estools.sethealth:
    description: Lets people set the health for themselves and others
    default: op
    
  estools.getinfo:
    description: Lets people get info about a player
    default: op
    
  estools.give:
    description: Lets people give themselves items
    default: op
    
  estools.reload:
    description: Lets people reload config files
    default: op
    
  estools.fix:
    description: Lets people repair items
    default: op
    
  estools.editsign:
    description: Lets people edit signs
    default: op
    
  estools.setstack:
    description: Lets people set the amount of itens in a stack
    default: op

  estools.clearinv:
    description: Lets people clear inventories
    default: op

  estools.time:
    description: Lets people change the time
    default: op

  estools.signs:
    description: Lets players make estools signs (like disposal)
    default: op
