main: net.estools.Entrypoints.EsToolsBukkit
name: EsTools
description: Simple highly compatible general purpose plugin.
version: '${project.version}'
softdepend: []
authors: [Calcilator, CoPokBl]
api-version: 1.13
folia-supported: true

commands:
  estools:
    description: View plugin information, including the version.
    usage: /estools [reload/reset/update/forceupdate/test/throw]
  gms:
    description: Change gamemode to survival.
    usage: /gms [player]
  gmc:
    description: Change gamemode to creative.
    usage: /gmc [player]
  gma:
    description: Change gamemode to adventure.
    usage: /gma [player]
  gmsp:
    description: Change gamemode to spectator.
    aliases: spec
    usage: /gmsp [player]
  tphere:
    description: Teleport a player to you.
    usage: /tphere <entity1> [entity2] [entity3]...
  tpall:
    description: Teleport all players to you.
    usage: /tpall [entity]
  feed:
    description: Fill saturation and hunger.
    usage: /feed [player]
  heal:
    description: Heal a player.
    usage: /heal [entity]
  sudo:
    description: Run a command as another player.
    usage: /sudo <player> <command>
  fly:
    description: Toggle flight.
    usage: /fly [player]
  suicide:
    description: End your own life.
    usage: /suicide
  smite:
    description: Strike player with lightning.
    usage: /smite <entity1> [entity2] [entity3]...
  sethealth:
    description: Set a player's health.
    usage: /sethealth <amount> [entity]
  setmaxhealth:
    description: Set a player's max health.
    usage: /setmaxhealth <amount> [entity]
  invsee:
    description: Open the inventory of another player.
    usage: /invsee <player>
  i:
    description: Give yourself an item.
    usage: /i <item> [amount]
  h:
    description: Put an item in your currently selected slot.
    usage: /h <item> [amount]
  ench:
    description: Enchant your currently held item.
    usage: /ench <enchantment> [level] [player]
  fix:
    description: Fully repair held item.
    usage: /fix [hand/offhand/helmet/chestplate/leggings/boots/all] [player]
  getinfo:
    description: Get information about an entity.
    usage: /getinfo <entity>
  editsign:
    description: Modify the text on a sign.
    usage: "/editsign <line> [text] or /editsign glow/unglow"
  god:
    description: Toggle god mode.
    usage: /god [entity] [time]
  music:
    description: Play a music disc.
    usage: /music [song]
  cchest:
    description: Open an ender chest like secondary inventory.
    usage: /cchest
  rename:
    description: Change the name held item.
    usage: /rename [text]
  back:
    description: Go to your location before you teleported/died.
    usage: /back
  setstack:
    description: Change the size of the held item stack.
    aliases: stack
    usage: /setstack <amount>
  ci:
    description: Clear your inventory.
    usage: /ci [player]
  powerpick:
    description: Give yourself an op pickaxe.
    aliases: pp
    usage: /pp
  poweraxe:
    description: Give yourself an op axe.
    aliases: pa
    usage: /pa
  powersword:
    description: Give yourself an op sword.
    aliases: ps
    usage: /ps
  powershovel:
    description: Give yourself an op shovel.
    aliases: psh
    usage: /psh
  powerhoe:
    description: Give yourself an op hoe.
    aliases: ph
    usage: /ph
  day:
    description: Set the time to day.
    usage: /day
  night:
    description: Set the time to night.
    aliases: moon
    usage: /night
  noon:
    description: Set the time to noon.
    usage: /noon
  midnight:
    description: Set the time to midnight.
    usage: /midnight
  rain:
    description: Set the weather to rain.
    usage: /rain
  sun:
    description: Set the weather to clear.
    usage: /rain
  thunder:
    description: Set the weather to thunderstorm.
    usage: /thunder
  walkspeed:
    description: Set your walk speed.
    usage: /walkspeed <speed> [players]
  flyspeed:
    description: Set your fly speed.
    usage: /flyspeed <speed> [players]
  setunbreakable:
    description: Toggle whether or not your held item is unbreakable.
    usage: /setunbreakable
  hideflags:
    description: Toggle whether or not your held item's flags are hidden.
    usage: /hideflags
  eff:
    description: Give a player a potion effect.
    usage: /eff <effect> [amplifier] [duration] [players]
  safetp:
    description: Toggle whether or not fall damage/distance should be kept when being teleported with commands.
    usage: /safetp
  infinite:
    description: Toggle whether or not you run out of items when placing blocks.
    usage: /infinite
  sethunger:
    description: Set a player's hunger level.
    usage: /sethunger <level> [player]
  setsaturation:
    description: Set a player's saturation level.
    usage: /setsaturation <level> [player]
  potion:
    description: Give a player a potion.
    usage: /potion <effect> [amplifier] [duration] [amount] [drink/splash/lingering] [player]
  bukkitdata:
    description: Set, get, and remove bukkit persistent nbt tags on items.
    usage: /bukkitdata <get/set/remove> <key> <type> <value>
  warp:
    description: Warp to saved locations.
    usage: /warp <warpname>
  warps:
    description: Create, Add, or Modify warps.
    usage: /warps <add/set> <warpname> [LOCAL/global] [x] [y] [z] [yaw] [pitch]
  lore:
    description: Add, Change, or Remove lore from items.
    usage: /lore add <text>, /lore set <line> <text>, /lore insert <line> <text>, /lore remove <line>
  mount:
    description: Make entities ride another entity.
    usage: /mount <ridee> [rider1] [rider2]...
  dismount:
    description: Make entities dismount other entities.
    usage: /dismount [rider1] [rider2]...
  buddha:
    description: Stop entities from dying from damage, their health will overflow back to full.
    usage: /buddha [entity] [time]
  disposal:
    description: Open an inventory that isn't saved so that you can place items and easily get rid of them.
    usage: /disposal

permissions:
  estools.update:
    description: Lets people update the plugin
    default: op

  estools.teleport:
    description: Lets people teleport themselves and others
    default: op

  estools.gamemode.survival:
    description: Lets people change the gamemode of themselves and others
    default: op

  estools.gamemode.creative:
    description: Lets people change the gamemode of themselves and others
    default: op

  estools.gamemode.adventure:
    description: Lets people change the gamemode of themselves and others
    default: op

  estools.gamemode.spectator:
    description: Lets people change the gamemode of themselves and others
    default: op
    
  estools.feed:
    description: Lets people feed themselves and others
    default: op
    
  estools.heal:
    description: Lets people heal themselves and others
    default: op
    
  estools.sudo:
    description: Lets people run commands as other players
    default: op
    
  estools.fly:
    description: Lets people toggle flight for themselves and others
    default: op
    
  estools.suicide:
    description: Lets people kill themselves
    default: true
    
  estools.smite:
    description: Lets people strike lightning on people
    default: op
    
  estools.sethealth:
    description: Lets people set the health for themselves and others
    default: op
    
  estools.setmaxhealth:
    description: Lets people set the max health for themselves and others
    default: op
    
  estools.getinfo:
    description: Lets people get info about a player
    default: op
    
  estools.invsee:
    description: Lets people see and edit other peoples inventories
    default: op
    
  estools.give:
    description: Lets people give themselves items
    default: op
    
  estools.reload:
    description: Lets people reload config files
    default: op
    
  estools.reset:
    description: Lets people reset all config files
    default: op
    
  estools.enchant:
    description: Lets people enchant items (unsafe enchantments allowed)
    default: op
    
  estools.fix:
    description: Lets people repair items
    default: op
    
  estools.editsign:
    description: Lets people edit signs
    default: op
    
  estools.god:
    description: Lets people turn invincible
    default: op
    
  estools.music:
    description: Lets people play music to themselves
    default: true
    
  estools.cchest.creative:
    description: Lets people have chests where they can store and use items anywhere
    default: true
    
  estools.cchest.survival:
    description: Lets people use cchests regardless of gamemode
    default: op
    
  estools.rename:
    description: Lets people rename items
    default: op
    
  estools.back:
    description: Lets people go back to nearest death location
    default: op
    
  estools.setstack:
    description: Lets people set the amount of itens in a stack
    default: op

  estools.clearinv:
    description: Lets people clear inventories
    default: op

  estools.powerpick:
    description: Lets people get an op pickaxe
    default: op

  estools.time:
    description: Lets people change the time
    default: op

  estools.weather:
    description: Lets people set the weather
    default: op

  estools.setunbreakable:
    description: Lets people make tools / weapons / armour unbreakable
    default: op

  estools.hideflags:
    description: Lets people hide flags like enchants.
    default: op

  estools.walkspeed:
    description: Lets players control walk speed
    default: op

  estools.flyspeed:
    description: Lets players control fly speed
    default: op

  estools.effect:
    description: Lets players set effects for themselves and others
    default: op

  estools.safetp:
    description: Lets players toggle if fall damage/distance should be kept when being teleported with commands
    default: op

  estools.signs:
    description: Lets players make estools signs (like disposal)
    default: op

  estools.infinite:
    description: Lets players not run out of items when placing blocks
    default: op

  estools.sethunger:
    description: Lets players set their and other peoples hunger level
    default: op

  estools.setsaturation:
    description: Lets players set their and other peoples saturation level
    default: op

  estools.potion:
    description: Lets players give themselves and others potions
    default: op

  estools.setpersistentdata:
    description: Lets players set, get, and remove bukkit persistent nbt tags on items.
    default: op

  estools.warps.use:
    description: Lets players use warps
    default: op

  estools.warps.manage:
    description: Lets players create, delete and edit warps
    default: op

  estools.warps.default:
    description: Is the default warp permission. If this is false, players will not be able to use a certain warp unless have estools.warp.<warpname>
    default: op

  estools.lore:
    description: Lets players add, change, or remove lore from items
    default: op

  estools.throw:
    description: Allows the player to throw a test exception for testing purposes
    default: op

  estools.version:
    description: Allows the player to view the plugin version, this allows the player to see that the server is running EsTools
    default: true

  estools.test:
    description: Allows the player the test all the EsTools commands using the builtin tester, the player still needs permissions for each individual command
    default: op

  estools.mount:
    description: Allows the player to make entities ride other entities
    default: op

  estools.disposal:
    description: Allows the player to open the disposal menu
    default: op